name: "Infra Preview Deploy"

on:
  push:
    branches:
      - main
    paths:
      - "10_infra/**"
      - ".github/workflows/**"
permissions:
  id-token: write
  contents: write

env:
  TF_VERSION: 1.2.8

defaults:
  run:
    shell: bash
    working-directory: 10_infra

jobs:
  preview:
    name: "preview"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: Terraform format
        run: terraform fmt -check
     