name: "Infra Destroy"

on:
  workflow_dispatch:  # 手動実行用のトリガー

permissions:
  id-token: write
  contents: write

env:
  AWS_REGION: ap-northeast-1
  TF_VERSION: 1.2.8
  TF_PROJECT: tastylog
  TF_ENVIRONMENT: dev
  
defaults:
  run:
    shell: bash
    working-directory: 10_infra

jobs:
  destroy:
    name: "destroy"
    runs-on: ubuntu-latest
    environment: production  # 本番環境の承認ワークフローを追加
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
      
      - name: Terraform init
        run: terraform init -no-color
      
      - name: Terraform destroy
        run: |
          terraform destroy -var project=${{ env.TF_PROJECT }} \
            -var environment=${{ env.TF_ENVIRONMENT }} \
            -var username=${{ secrets.MYSQL_USERNAME}} \
            -var password=${{ secrets.MYSQL_PASSWORD }} \
            -auto-approve -input=false -no-color 